# Generated by Django 4.0.5 on 2022-06-04 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='short_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='long_description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
    ]
