# Generated by Django 4.0.5 on 2022-06-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
