# Generated by Django 4.0.4 on 2022-05-24 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_place_place_city_remove_place_place_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100, unique=True)),
                ('event_description', models.CharField(max_length=100)),
                ('event_start_date', models.DateTimeField()),
                ('event_end_date', models.DateTimeField()),
                ('event_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.place')),
            ],
        ),
    ]
